name: fix cover

on:
  workflow_dispatch:
jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    env:
        NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        NOTION_PAGE: ${{ secrets.NOTION_PAGE }}
        KEEP_MOBILE: ${{ secrets.KEEP_MOBILE }}
        KEEP_PASSWORD: ${{ secrets.KEEP_PASSWORD }}
        YEAR: ${{ vars.YEAR }}
        REPOSITORY: ${{ github.repository }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: fix cover
        run: |
          python -u scripts/cover.py